export const languages = {
  zh: '中文',
  en: 'English',
} as const;

export const defaultLang = 'zh' as const;

export const ui = {
  zh: {
    'site.title': '鬼哥的 AI 行业每日简报',
    'site.description': '每日自动生成的 AI 行业金融分析与投资简报',
    'nav.home': '首页',
    'nav.archive': '历史归档',
    'nav.subscribe': '订阅',
    'home.latestBriefing': '最新简报',
    'home.readFull': '阅读完整报告',
    'home.recentReports': '近期报告',
    'home.viewAll': '查看全部',
    'archive.title': '历史归档',
    'archive.description': '所有每日简报按日期排列',
    'report.slides': '幻灯片',
    'report.infographic': '信息图',
    'report.backToHome': '返回首页',
    'report.backToArchive': '返回归档',
    'subscribe.title': '订阅简报',
    'subscribe.description': '每日自动推送 AI 行业投资简报到你的邮箱',
    'subscribe.emailPlaceholder': '输入邮箱地址',
    'subscribe.button': '订阅',
    'subscribe.rss': 'RSS 订阅',
    'subscribe.rssHint': '使用 RSS 阅读器订阅获取每日更新',
    'footer.disclaimer': '免责声明：本报告仅供参考，不构成投资建议。',
    'footer.poweredBy': '由 Finance Briefing Agent 自动生成',
    'noReports': '暂无报告',
  },
  en: {
    'site.title': 'AI Industry Daily Briefing',
    'site.description': 'Auto-generated daily AI industry financial analysis and investment briefing',
    'nav.home': 'Home',
    'nav.archive': 'Archive',
    'nav.subscribe': 'Subscribe',
    'home.latestBriefing': 'Latest Briefing',
    'home.readFull': 'Read Full Report',
    'home.recentReports': 'Recent Reports',
    'home.viewAll': 'View All',
    'archive.title': 'Archive',
    'archive.description': 'All daily briefings sorted by date',
    'report.slides': 'Slides',
    'report.infographic': 'Infographic',
    'report.backToHome': 'Back to Home',
    'report.backToArchive': 'Back to Archive',
    'subscribe.title': 'Subscribe',
    'subscribe.description': 'Get daily AI industry investment briefings delivered to your inbox',
    'subscribe.emailPlaceholder': 'Enter your email',
    'subscribe.button': 'Subscribe',
    'subscribe.rss': 'RSS Feed',
    'subscribe.rssHint': 'Subscribe via RSS reader for daily updates',
    'footer.disclaimer': 'Disclaimer: This report is for reference only and does not constitute investment advice.',
    'footer.poweredBy': 'Auto-generated by Finance Briefing Agent',
    'noReports': 'No reports yet',
  },
} as const;

export type Lang = keyof typeof ui;
type UiKey = keyof (typeof ui)['zh'];

export function t(lang: Lang, key: UiKey): string {
  return ui[lang][key] || ui[defaultLang][key] || key;
}

export function getBasePath(lang: Lang): string {
  const base = '/fin-report';
  return lang === 'en' ? `${base}/en` : base;
}
